services:
  hello-world:
    build:
      context: https://github.com/greenfrontend/hello-world
      dockerfile: /Dockerfile
    environment:
      KEY: VALUE
    deploy:
      resources:
        limits:
          memory: 250M
  another-container:
    build:
      context: https://github.com/greenfrontend/hello-world
      dockerfile: /Dockerfile
    environment:
      KEY: VALUE
    deploy:
      resources:
        limits:
          memory: 250M

x-uffizzi:
  ingress:
    service: hello-world
    port: 80

  continuous_preview:
    share_to_github: true
    delete_preview_after: 1h
    delete_preview_when_image_tag_is_updated: true
    deploy_preview_when_image_tag_is_created: true
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
